# Generated by Django 4.2.6 on 2023-12-26 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_textmessage_from_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='textmessage',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.room'),
        ),
        migrations.AlterField(
            model_name='textmessage',
            name='text',
            field=models.TextField(),
        ),
    ]
