# Generated by Django 4.2.6 on 2023-12-26 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_textmessage_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='textmessage',
            old_name='text',
            new_name='text_data',
        ),
    ]
